### ISSUE TITLE
Error with "Test-SecretVault" in pre-release 0.9.2

### ISSUE THREAD

**Issue by NJK-HOME** [JustinGrote/SecretManagement.KeePass#48] opened 2021-04-18 05:31 UTC
When attempting to use Test-SecretVault with your latest pre-release of 0.9.2, I get this error:

PS> Test-SecretVault -Name SomeVaultName
Import-Module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:12 char:27
                 $module = Import-Module -Name $ModulePath -PassThru
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
     FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
False

I have tried this in both Windows PowerShell 5.1 and PowerShell 7.1.3.  Same error in both.

**Comment by JustinGrote** [comment] 2021-04-19 01:46
Dupe of #47 (fixed)

**Closed by JustinGrote** 2021-04-19 01:46 UTC
Labels: bug
